package com.haiqiu.nature.dao;

import com.haiqiu.nature.entity.Animal;
import com.haiqiu.nature.entity.AnimalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnimalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int countByExample(AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int deleteByExample(AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int insert(Animal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int insertSelective(Animal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    List<Animal> selectByExample(AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    Animal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Animal record, @Param("example") AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Animal record, @Param("example") AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Animal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Animal record);
}